"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Yatoo.py']
DATA_FILES = ['morse_code.py', 'caesar_cipher.py', 'rail_fence_cipher.py', 'oldCode.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
